#!/bin/bash

### CPU usage ###
read cpu user nice system idle iowait irq softirq steal guest guest_nice </proc/stat
total1=$((user + nice + system + idle + iowait + irq + softirq + steal))
idle1=$((idle + iowait))

sleep 0.5

read cpu user nice system idle iowait irq softirq steal guest guest_nice </proc/stat
total2=$((user + nice + system + idle + iowait + irq + softirq + steal))
idle2=$((idle + iowait))

delta_total=$((total2 - total1))
delta_idle=$((idle2 - idle1))

cpu_usage=$((100 * (delta_total - delta_idle) / (delta_total)))

### CPU temperature ###
cpu_temp=$(sensors | awk '/Package id 0/ {print int($4)}/Tctl/ {print $2}' | head -n1 | tr -d '+°C')

font_color=^c#458588^
bg_color=^b#282828^
echo "$font_color$bg_color""CPU $cpu_usage% $cpu_temp° ^d^"
