#!/bin/sh

# CPU usage
read cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat
total1=$((user + nice + system + idle + iowait + irq + softirq + steal))
idle1=$((idle + iowait))

sleep 0.5

read cpu user nice system idle iowait irq softirq steal guest guest_nice < /proc/stat
total2=$((user + nice + system + idle + iowait + irq + softirq + steal))
idle2=$((idle + iowait))

cpu_usage=$((100 * ((total2 - total1) - (idle2 - idle1)) / (total2 - total1)))

# CPU temperature
if [ -f /sys/class/thermal/thermal_zone0/temp ]; then
    cpu_temp=$(( $(cat /sys/class/thermal/thermal_zone0/temp) / 1000 ))
else
    cpu_temp="N/A"
fi

font_color=^c#ebdbb2^
bg_color=^b#458588^ # blue
echo $font_color$bg_color CPU $cpu_usage% $cpu_temp°C ^d^


