#!/bin/bash

command -v nvidia-smi >/dev/null 2>&1 || exit

font_color=^c#b8bb261^
bg_color=^b#282828^
gpu_usage=$(nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits)
gpu_temp=$(nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader,nounits)

echo "$font_color$bg_color""GPU $gpu_usage% $gpu_temp° ^d^"
