#!/bin/bash

font_color=^c#fb4934^
bg_color=^b#282828^

mem=$(free | awk '/^Mem:/ {printf "%.0f%%", $3/$2 * 100}')

echo "${font_color}${bg_color}""MEM ${mem} ^d^"

# CURRENT / TOTAL
# font_color=^c#fb4934^
# bg_color=^b#282828^
# mem=$(free -h | awk '/^Mem/ {print $3 "/" $2}' | sed 's/i//g')

# echo $font_color$bg_color MEM $mem ^d^
